FROM openjdk:8u212-jre
MAINTAINER Authur 1048146644@qq.com

COPY authur-server-test-1.0-SNAPSHOT.jar /authur/authur-server-test-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/authur/authur-server-test-1.0-SNAPSHOT.jar"]
