global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['81.70.92.153:8403']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['81.70.92.153:8405']
        labels:
          instance: 'node_exporter'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['81.70.92.153:8407']
        labels:
          instance: 'cadvisor'
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['81.70.92.153:8408']
        labels:
          instance: 'redis_exporter'
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['81.70.92.153:8409']
        labels:
          instance: 'mysql_exporter'

  - job_name: 'authur-server-auth-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['81.70.92.153:8101']
        labels:
          instance: 'authur-auth'
  - job_name: 'authur-server-system-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['81.70.92.153:8201']
        labels:
          instance: 'authur-server-system'
  - job_name: 'authur-server-test-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['81.70.92.153:8202']
        labels:
          instance: 'authur-server-test'
rule_files:
  - 'memory_over.yml'
  - 'server_down.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["81.70.92.153:8406"]
