global:
  smtp_smarthost: 'smtp.126.com:465'
  smtp_from: 'Authur104@126.com'
  smtp_auth_username: 'Authur104'
  smtp_auth_password: 'GKXGHKAHTRUBXGTX'
  smtp_require_tls: false

#templates:
##  - '/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
    group_wait: 10s
      group_interval: 5m
        repeat_interval: 5m
          receiver: 'default-receiver'

          receivers:
            - name: 'default-receiver'
                email_configs:
                      - to: '1048146644@qq.com'
                              send_resolved: true
